//day011919154726.file.core.windows.net/fsshare1|/mnt/appdatalocal|/etc/smbcredentials/appdatalocal.cred
//day011919154726.file.core.windows.net/datashare1|/mnt/transactiondata|/etc/smbcredentials/transactiondata.cred
//prodfileshare21.file.core.windows.net/storebackup|/mnt/backupdata|/etc/smbcredentials/backupdata.cred
